apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: o2vuu4u8o-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/o2vuu4u8o-dotnet-basic-gitops